CREATE TABLE all_candidates (
  CAND_ID VARCHAR(9),
  CAND_NAME VARCHAR(200),
  CAND_ICI VARCHAR (1),
  PTY_CD VARCHAR (1),
  CAND_PTY_AFFILIATION VARCHAR (3),
  TTL_RECEIPTS DECIMAL (14,2),
  TRANS_FROM_AUTH DECIMAL (14,2),
  TTL_DISB DECIMAL (14,2),
  TRANS_TO_AUTH DECIMAL (14,2),
  COH_BOP DECIMAL (14,2),
  COH_COP DECIMAL (14,2),
  CAND_CONTRIB DECIMAL (14,2),
  CAND_LOANS DECIMAL (14,2),
  OTHER_LOANS DECIMAL (14,2),
  CAND_LOAN_REPAY DECIMAL (14,2),
  OTHER_LOAN_REPAY DECIMAL (14,2),
  DEBTS_OWED_BY DECIMAL (14,2),
  TTL_INDIV_CONTRIB DECIMAL (14,2),
  CAND_OFFICE_ST VARCHAR (2),
  CAND_OFFICE_DISTRICT VARCHAR (2),
  SPEC_ELECTION VARCHAR (1),
  PRIM_ELECTION VARCHAR (1),
  RUN_ELECTION VARCHAR (1),
  GEN_ELECTION VARCHAR (1),
  GEN_ELECTION_PRECENT DECIMAL (7,4),
  OTHER_POL_CMTE_CONTRIB DECIMAL (14,2),
  POL_PTY_CONTRIB DECIMAL (14,2),
  CVG_END_DT DATE,
  INDIV_REFUNDS DECIMAL (14,2),
  CMTE_REFUNDS DECIMAL (14,2)
);


CREATE TABLE candidate_committee_linkage
(
  CAND_ID VARCHAR (9) REFERENCES all_candidates(CAND_ID),
  CAND_ELECTION_YR INT,
  FEC_ELECTION_YR INT,
  CMTE_ID VARCHAR (9),
  CMTE_TP VARCHAR (1),
  CMTE_DSGN VARCHAR (1),
  LINKAGE_ID INT
);

CREATE TABLE committee_master
(
  CMTE_ID VARCHAR(9),
  CMTE_NM VARCHAR(200),
  TRES_NM VARCHAR(90),
  CMTE_ST1 VARCHAR(34),
  CMTE_ST2 VARCHAR(34),
  CMTE_CITY VARCHAR(30),
  CMTE_ST VARCHAR(2),
  CMTE_ZIP VARCHAR(9),
  CMTE_DSGN VARCHAR(1),
  CMTE_TP VARCHAR(1),
  CMTE_PTY_AFFILIATION VARCHAR(3),
  CMTE_FILING_FREQ VARCHAR(1),
  ORG_TP VARCHAR(1),
  CONNECTED_ORG_NM VARCHAR(200),
  CAND_ID VARCHAR(9)
);

CREATE TABLE pac_summary
(
  CMTE_ID VARCHAR (9),
  CMTE_NM VARCHAR (200),
  CMTE_TP VARCHAR (1),
  CMTE_DSGN VARCHAR (1),
  CMTE_FILING_FREQ VARCHAR (1),
  TTL_RECEIPTS DECIMAL(14,2),
  TRANS_FROM_AFF DECIMAL(14,2),
  INDV_CONTRIB DECIMAL(14,2),
  OTHER_POL_CMTE_CONTRIB DECIMAL(14,2),
  CAND_CONTRIB DECIMAL(14,2),
  CAND_LOANS DECIMAL(14,2),
  TTL_LOANS_RECEIVED DECIMAL(14,2),
  TTL_DISB DECIMAL(14,2),
  TRANF_TO_AFF DECIMAL(14,2),
  INDV_REFUNDS DECIMAL(14,2),
  OTHER_POL_CMTE_REFUNDS DECIMAL(14,2),
  CAND_LOAN_REPAY DECIMAL(14,2),
  LOAN_REPAY DECIMAL(14,2),
  COH_BOP DECIMAL(14,2),
  COH_COP DECIMAL(14,2),
  DEBTS_OWED_BY DECIMAL(14,2),
  NONFED_TRANS_RECEIVED DECIMAL(14,2),
  CONTRIB_TO_OTHER_CMTE DECIMAL(14,2),
  IND_EXP DECIMAL(14,2),
  PTY_COORD_EXP DECIMAL(14,2),
  NONFED_SHARE_EXP DECIMAL(14,2),
  CVG_END_DT VARCHAR(11)
);

CREATE TABLE contributions_to_candidates
(
  CMTE_ID VARCHAR (9),
  AMNDT_IND VARCHAR (1),
  RPT_TP VARCHAR (3),
  TRANSACTION_PGI	VARCHAR (5),
  IMAGE_NUM VARCHAR(18),
  TRANSACTION_TP	VARCHAR (3),
  ENTITY_TP VARCHAR (3),
  NAME VARCHAR (200),
  CITY VARCHAR (30),
  STATE VARCHAR (2),
  ZIP_CODE VARCHAR (9),
  EMPLOYER VARCHAR (38),
  OCCUPATION 	VARCHAR (38),
  TRANSACTION_DT VARCHAR(11),
  TRANSACTION_AMT DECIMAL (14,2),
  OTHER_ID VARCHAR (9),
  CAND_ID VARCHAR (9),
  TRAN_ID VARCHAR (32),
  FILE_NUM DECIMAL (22),
  MEMO_CD VARCHAR (1),
  MEMO_TEXT VARCHAR (100),
  SUB_ID DECIMAL (19)
);

CREATE TABLE committee_to_committee
(
  CMTE_ID VARCHAR (9),
AMNDT_IND VARCHAR (1),
RPT_TP VARCHAR (3),
TRANSACTION_PGI VARCHAR (5),
IMAGE_NUM VARCHAR(18),
TRANSACTION_TP VARCHAR (3),
ENTITY_TP 	VARCHAR (3),
NAME VARCHAR (200),
CITY VARCHAR (30),
STATE VARCHAR (2),
ZIP_CODE VARCHAR (9),
EMPLOYER VARCHAR (38),
OCCUPATION VARCHAR (38),
TRANSACTION_DT 	VARCHAR(11),
TRANSACTION_AMT DECIMAL (14,2),
OTHER_ID VARCHAR (9),
TRAN_ID VARCHAR (32),
FILE_NUM DECIMAL (22),
MEMO_CD VARCHAR (1),
MEMO_TEXT VARCHAR (100),
SUB_ID 	DECIMAL (19)
);

